spring:
  datasource:
    url: jdbc:h2:mem:weekend_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


